### ISSUE TITLE
bug,服务注册不支持集群

### ISSUE THREAD

**Issue by Kalen2** [catcherwong/nacos-sdk-csharp#19]
"ServerAddresses": [ "http://localhost:8848", "http://192.168.10.22:8848" ]配置多个地址时，只注册了第一个

**Comment by catcherwong** [comment]
@Kalen2  谢谢您对这个项目感兴趣！

您好，请问您的集群是怎么搭建的？

**Comment by Kalen2** [comment]
@catcherwong 我就2台电脑分别启动了nacos。然后ServerAddresses": [ "http://localhost:8848", "http://192.168.10.22:8848" ]配置多个地址，也不知道这样对不对？

**Comment by catcherwong** [comment]
建议参考nacos官网。

https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

**Comment by Kalen2** [comment]
我看java上nacos地址是可以多个啊。
"nacos": {
    "ServerAddresses": [ "http://192.168.4.28:8848", "http://192.168.4.28:8849" ],
    "DefaultTimeOut": 15,
    "Namespace": "",
    "ListenInterval": 1000,
    "ServiceName": "App3"
    //"GroupName": "public"
  }

当我配置多个地址时：
D:\demo\cbi\netcore\net-core3\nacos-sdk-csharp\samples\App3\bin\Debug\netcoreapp3.1>dotnet App3.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nacos.AspNetCore.StatusReportBgTask.GetUri(IFeatureCollection features, NacosAspNetCoreOptions config) in D:\demo\cbi\netcore\net-core3\nacos-sdk-csharp\src\Nacos.AspNetCore\StatusReportBgTask.cs:line 167
   at Nacos.AspNetCore.StatusReportBgTask.StartAsync(CancellationToken cancellationToken) in D:\demo\cbi\netcore\net-core3\nacos-sdk-csharp\src\Nacos.AspNetCore\StatusReportBgTask.cs:line 40
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at App3.Program.Main(String[] args) in D:\demo\cbi\netcore\net-core3\nacos-sdk-csharp\samples\App3\Program.cs:line 10

D:\demo\cbi\netcore\net-core3\nacos-sdk-csharp\samples\App3\bin\Debug\netcoreapp3.1>

**Comment by Kalen2** [comment]
"nacos": {
    "ServerAddresses": [ "http://192.168.4.2833:8848", "http://192.168.4.28:8849" ],
    "DefaultTimeOut": 15,
    "Namespace": "",
    "ListenInterval": 1000,
    "ServiceName": "App3"
    //"GroupName": "public"
  }
ServerAddresses配置多个时，如果第一个IP是错的。就不会往下走了，导致服务注册不上。

**Comment by catcherwong** [comment]
升级到最新版试试，最新版有对失败做处理。

https://github.com/catcherwong/nacos-sdk-csharp/blob/61e8efd7865e7a48fca5c85d63e1bf2e27730348/src/Nacos/Naming/Http/NamingProxy.cs#L185-L199
