### ISSUE TITLE
Program.cs Main报空异常

### ISSUE THREAD

**Issue by huangli321456** [catcherwong/nacos-sdk-csharp#31]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Nacos.AspNetCore
  StackTrace:
   at Nacos.AspNetCore.StatusReportBgTask.GetUri(IFeatureCollection features, NacosAspNetCoreOptions config)
   at Nacos.AspNetCore.StatusReportBgTask.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Product.Api.Program.Main(String[] args) in D:\CoreProjects\NetCoreMicroserviceDemo\Product.Api\Program.cs:line 16

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    Product.Api.Program.Main(string[]) (位于 Program.cs 中)

**Comment by catcherwong** [comment]
@huangli321456 谢谢您对这个项目感兴趣！

> at Nacos.AspNetCore.StatusReportBgTask.GetUri(IFeatureCollection features, NacosAspNetCoreOptions config)

看是去是没有获取到对应的URL地址，可以看一下具体的配置吗？还有使用的版本是那个？

**Comment by huangli321456** [comment]
.netcore3.1的，sdk是nuget上获取的最新版nacos csharp sdk (unofficial)0.027，配置都是根据你上面写的
appsetting.json:
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "nacos": {
    "ServerAddresses": [ "http://localhost:8848" ],
    "DefaultTimeOut": 15000,
    "Namespace": "",
    "ListenInterval": 1000,
    "ServiceName": "App1"
  }
}
